---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - curl
    update_cache: true
    state: present
  become: true

- name: Add Caddy GPG key
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    dest: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    mode: 0644
  become: true

- name: Add Caddy repository to sources list
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    state: present
  become: true

- name: Add Caddy src repository to sources list
  ansible.builtin.apt_repository:
    repo: "deb-src [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    state: present
  become: true

- name: Install Caddy
  ansible.builtin.apt:
    name: caddy
    state: present
    update_cache: true
  become: true

- name: Start Caddy
  ansible.builtin.service:
    name: caddy
    state: started
    enabled: true
  become: true
