---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - curl
    update_cache: true
    state: present
  become: true

- name: Add Caddy repository to sources list
  ansible.builtin.apt_repository:
    repo: "deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian
      any-version main"
    state: present
    filename: caddy-stable
  become: true

- name: Add Caddy src repository to sources list
  ansible.builtin.apt_repository:
    repo: "deb-src https://dl.cloudsmith.io/public/caddy/stable/deb/debian
      any-version main"
    state: present
    filename: caddy-stable
  become: true

- name: Install Caddy
  ansible.builtin.apt:
    name: caddy
    state: present
    update_cache: true
  become: true

- name: Start Caddy
  ansible.builtin.service:
    name: caddy
    state: started
    enabled: true
  become: true
