---
- name: Set fact swap_file_path and swap_file_size_mb
  ansible.builtin.set_fact:
    swap_file_path: "{{ swap_file_path | default('/swapfile') }}"
    swap_file_size_mb: "{{ swap_file_size_mb | default('8192') }}"

- name: Check if swap file exists
  ansible.builtin.stat:
    path: "{{ swap_file_path }}"
  register: swap_file

- name: Set fact swap_file_existing_size_mb if swap file exists
  ansible.builtin.set_fact:
    swap_file_existing_size_mb: "{{ (swap_file.stat.size / 1024 / 1024) | int }}"
  when: swap_file.stat.exists

- name: Set fact swap_file_existing_size_mb to 0 if not swap file exists
  ansible.builtin.set_fact:
    swap_file_existing_size_mb: "0"
  when: not swap_file.stat.exists
