---
- name: Create swap file
  ansible.builtin.command: dd if=/dev/zero of="{{ swap_file_path }}" bs=1M count={{ swap_file_size_mb }}
  become: true
  when: not swap_file.stat.exists

- name: Set swap file permissions
  ansible.builtin.file:
    path: "{{ swap_file_path }}"
    owner: root
    ansible.builtin.group: root
    mode: 0600
  become: true
  when: not swap_file.stat.exists

- name: Make swap file
  ansible.builtin.command: mkswap "{{ swap_file_path }}"
  become: true
  when: not swap_file.stat.exists

- name: Enable swap file
  ansible.builtin.command: swapon -a
  become: true
  when: not swap_file.stat.exists

- name: Mount swap file
  ansible.posix.mount:
    name: none
    src: "{{ swap_file_path }}"
    fstype: swap
    opts: sw
    state: present
  become: true
