---
- name: Check
  ansible.builtin.include_tasks:
    ansible.builtin.file: check.yml
  when:
    - not skip_swap | default(false)
    - ansible_virtualization_type != 'lxc'

- name: Disable
  ansible.builtin.include_tasks:
    ansible.builtin.file: disable.yml
  when:
    - not skip_swap | default(false)
    - ansible_virtualization_type != 'lxc'
    - swap_file_existing_size_mb != 0
    - swap_file_existing_size_mb != swap_file_size_mb

- name: Enable
  ansible.builtin.include_tasks:
    ansible.builtin.file: enable.yml
  when:
    - not skip_swap | default(false)
    - ansible_virtualization_type != 'lxc'
    - swap_file_existing_size_mb != swap_file_size_mb
