---
- name: Install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true

- name: Enable docker
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true
  become: true
