---
- name: Install Zabbix Package
  ansible.builtin.apt:
    deb: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb"
  become: true

- name: Install Zabbix Agent
  ansible.builtin.apt:
    name:
      - zabbix-agent2
      - zabbix-agent2-plugin-*
    update_cache: true
    state: present
  become: true
  notify: start zabbix-agent
