---
- name: Put wings.service
  ansible.builtin.copy:
    src: ./etc/systemd/system/wings.service
    dest: /etc/systemd/system/wings.service
    owner: root
    group: root
    mode: 0644
  become: true

- name: Enable wings service
  ansible.builtin.systemd_service:
    name: wings
    enabled: true
    state: started
  become: true
