---
- name: Make sure /etc/systemd/resolved.conf.d directory exists
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true
  notify:
    - restart systemd-resolved

- name: Copy systemd-resolved configuration
  ansible.builtin.copy:
    src: ./etc/systemd/resolved.conf.d/internal.conf
    dest: /etc/systemd/resolved.conf.d/internal.conf
  become: true
  notify:
    - restart systemd-resolved
