---
- name: Create infra user
  user:
    name: "{{ user_infra_name }}"
    uid: 1000
    password: "{{ user_infra_password | password_hash( 'sha512', user_infra_salt ) }}"
    update_password: always
    group: infra
    groups: sudo
    shell: /bin/bash
    create_home: true
    home: /home/infra
    state: present

- name: Copy ssh private key
  ansible.builtin.copy:
    content: "{{ user_infra_ssh_private_key }}"
    dest: "/home/{{ user_infra_name }}/.ssh/infra"
    mode: 0600
    owner: "{{ user_infra_name }}"
    group: "{{ user_infra_name }}"

- name: Set authorized key
  authorized_key:
    user: "{{ user_infra_name }}"
    state: present
    key: "{{ lookup('file', './infra_id_ed25519.pub') }}"
