---
- name: install dependencies
  ansible.builtin.include_tasks:
    file: dependencies.yml

- name: install kitsunebi
  ansible.builtin.include_tasks:
    file: install.yml

- name: Setup kitsunebi cron jobs
  ansible.builtin.include_tasks:
    file: cron.yml
